#!/bin/sh -e
#
# Copyright 2015 Al Nikolov
#
# This file is part of ocds-ru suite.
#
#    ocds-ru is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ocds-ru is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with ocds-ru.  If not, see <http://www.gnu.org/licenses/>.
#

if basename $1 | grep ^contractProcedure_; then
        parent=$(find $PROCS_DIR -name $(xsltproc linkup.xslt $1)_* -print -quit)
        [ -z "$parent" ] && echo "Unable to linkup" && exit 1
        basename $(dirname $parent) > $2
else
        touch $2
fi
