#!/bin/sh -e
# Copyright 2015 Al Nikolov

SOURCE=ftp://free:free@ftp.zakupki.gov.ru
MIRROR=mirror
WORK=work

# Set these to only one region
SRC_DIR=fcs_regions/Adygeja_Resp
DST_DIR=$SRC_DIR

lftp $SOURCE -e "mirror $SRC_DIR $MIRROR/$DST_DIR -c -e --no-empty-dirs -P5 -v 1 -X notifications/ -X plangraphs/ -X protocols/ -X purchasedocs/ -X sketchplans/ -X prevMonth/; exit"

REGION_DIRS=$(find $MIRROR/fcs_regions -mindepth 1 -maxdepth 1 -type d)
for REGION_DIR in $REGION_DIRS; do
  REGION=$(basename $REGION_DIR)
  for DOC_TYPE in contracts; do
      ZIPS=$(find $REGION_DIR/$DOC_TYPE -name *.zip)
      if [ -n "$ZIPS" ]; then
          mkdir -p $WORK/$REGION/$DOC_TYPE
          for ZIP in $ZIPS; do
            unzip -jn $ZIP -d $WORK/$REGION/$DOC_TYPE || [ $? -eq 1 ]
          done
      fi
  done
done
