#!/bin/sh -e
#
# Copyright 2015 Al Nikolov
#
# This file is part of ocds-ru suite.
#
#    ocds-ru is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ocds-ru is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with ocds-ru.  If not, see <http://www.gnu.org/licenses/>.
#
eval $(xsltproc process.xslt $1)
if [ -z "$ocid" ]; then
        parent=$(find $PROCS_DIR -type f -name $(echo $id | cut -f1 -d_)_*.xml -print -quit)
        [ -z "$parent" ] && echo "Unable to linkup" && exit 1
        ocid=$(basename $(dirname $parent))
        xsltproc -stringparam ocid $ocid -o $1.linkup linkup.xslt $1
        mv $1.linkup $1 
fi
mkdir -p $PROCS_DIR/$ocid
cp $1 $PROCS_DIR/$ocid/$id.xml
touch -d $date $PROCS_DIR/$ocid/$id.xml
touch $2

